apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ep5t
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-ep5t@sha256:9db26617d7297878fa70ca6b8d983761b39762dbd4dfc8386277c7433c89ecdf
        name: my-nodejs
        resources: {}
status: {}
